    version: '3.9'
    services:
      app:
        container_name: "jira"
        build:
          context: .
          dockerfile: Dockerfile
        image: jira
        ports:
          - "8080:8080"
        depends_on:
          - postgres
          - nginx
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jira
          SPRING_DATASOURCE_USERNAME: jira
          SPRING_DATASOURCE_PASSWORD: JiraRush
          SPRING_PROFILES_ACTIVE: prod
          DATASOURCE_URL: jdbc:postgresql://localhost:5432/jira
          DATASOURCE_USERNAME: jira
          DATASOURCE_PASSWORD: JiraRush
          MAIL_HOST: smtp.gmail.com
          MAIL_USERNAME: jira4jr@gmail.com
          MAIL_PASSWORD: zdfzsrqvgimldzyj
          MAIL_PORT: 587
          OAUTH2_REGISTRATION_GITHUB_ID: 3d0d8738e65881fff266
          OAUTH2_REGISTRATION_GITHUB_SECRET: 0f97031ce6178b7dfb67a6af587f37e222a16120
          OAUTH2_REGISTRATION_GOOGLE_ID: 329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com
          OAUTH2_REGISTRATION_GOOGLE_SECRET: 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
          OAUTH2_REGISTRATION_GITLAB_ID: b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494
          OAUTH2_REGISTRATION_GITLAB_SECRET: e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004
          GITLAB_AUTHORIZATION_URI: https://gitlab.com/oauth/authorize
          GITLAB_TOKEN_URI: https://gitlab.com/oauth/token
          GITLAB_USER_INFO_URI: https://gitlab.com/api/v4/user
          GITLAB_USER_NAME_ATTRIBUTE: email
      postgres:
        image: postgres
        environment:
          POSTGRES_USER: jira
          POSTGRES_PASSWORD: JiraRush
          POSTGRES_DB: jira
        ports:
          - "5432:5432"
      nginx:
        image: nginx
        container_name: nginx
        volumes:
          - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
        ports:
          - "80:80"