#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
app:
  host-url: http://localhost:8080
  test-mail: ${MAIL_USERNAME}
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: ${MAIL_CORE_POOL_SIZE}
    max-pool-size: ${MAIL_MAX_POOL_SIZE}

spring:
  jpa:
    show-sql: true
    open-in-view: false

# validate db by model
    hibernate:
      ddl-auto: validate

    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  liquibase:
    changeLog: "classpath:db/changelog.sql"

  # Jackson Fields Serialization
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
    cache-names: users
    caffeine.spec: maximumSize=10000,expireAfterAccess=5m

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_REGISTRATION_GITHUB_ID}
            client-secret: ${OAUTH2_REGISTRATION_GITHUB_SECRET}
            scope:
              - email
          google:
            client-id: ${OAUTH2_REGISTRATION_GOOGLE_ID}
            client-secret: ${OAUTH2_REGISTRATION_GOOGLE_SECRET}
            scope:
              - email
              - profile
          gitlab:
            client-id: ${OAUTH2_REGISTRATION_GITLAB_ID}
            client-secret: ${OAUTH2_REGISTRATION_GITLAB_SECRET}
            client-name: GitLab
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          gitlab:
            authorization-uri: ${GITLAB_AUTHORIZATION_URI}
            token-uri: ${GITLAB_TOKEN_URI}
            user-info-uri: ${GITLAB_USER_INFO_URI}
            user-name-attribute: ${GITLAB_USER_NAME_ATTRIBUTE}

  sql:
    init:
      mode: always

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
  thymeleaf.check-template-location: false

  config:
    location: app.properties


logging:
  level:
    root: WARN
    com.javarush.jira: DEBUG
    com.javarush.jira.common.config.MvcConfig: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server:
#  https://springdoc.org/index.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true
springdoc.swagger-ui.path: /doc
